### ISSUE TITLE
Typo delta_reward / delat_reward

### ISSUE THREAD

**Issue by JoostvDoorn** [apeterswu/RL4NMT#2]
I was looking through the code a bit and found that delta_reward had a typo here:

https://github.com/apeterswu/RL4NMT/blob/ab8d9fdceca68c9218b6c3ee3c9bd812c5f9b47a/tensor2tensor/utils/bleu_hook.py#L273
and
https://github.com/apeterswu/RL4NMT/blob/ab8d9fdceca68c9218b6c3ee3c9bd812c5f9b47a/tensor2tensor/utils/bleu_hook.py#L293

Don't think this affects the experiments, but the unused_kwargs is pretty dangerous so worth checking.

**Comment by apeterswu** [comment]
Thanks for your interest and detailed checking. I have fixed the typo and checked the reference, the experiments are not affected. But this is worth, thanks again.
