### ISSUE TITLE
Data Preps for training ?

### ISSUE THREAD

**Issue by yashkumaratri** [apeterswu/RL4NMT#4]
I went through tensor2tensor and looked for data generation but couldn't find the problem which will prep the data for training for your code, zh-en is not supported. Can you please help?
The script says that putting _rev will make the data for zh-en task but it does not work.Only en-zh work, So ?

**Comment by apeterswu** [comment]
Please refer to RL4NMT/zhen_wmt17/zhen_wmt17.py and have a check, it is for zh-en task.
